dist: trusty
language: python
env:
  matrix:
    - TOXENV=py27-django-18
    - TOXENV=py27-django-19
    - TOXENV=py27-django-110
    - TOXENV=py27-django-111
    - TOXENV=py33-django-18
    - TOXENV=py34-django-18
    - TOXENV=py34-django-19
    - TOXENV=py34-django-110
    - TOXENV=py34-django-111
    - TOXENV=py35-django-18
    - TOXENV=py35-django-19
    - TOXENV=py35-django-110
    - TOXENV=py35-django-111
    - TOXENV=py35-django-master
  global:
    - PIP_WHEEL_DIR=$HOME/.wheels
    - PIP_FIND_LINKS=file://$HOME/.wheels
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36-django-111
    - python: 3.6
      env: py36-django-master
install:
    - mkdir -p $PIP_WHEEL_DIR
    - pip wheel -r tests/requirements.txt tox coveralls
    - pip install coveralls tox
script:
  - tox
after_success:
  - coveralls
