dist: xenial
language: python
env:
  global:
    - PIP_WHEEL_DIR=$HOME/.wheels
    - PIP_FIND_LINKS=file://$HOME/.wheels
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-django-111
    - python: 3.4
      env: TOXENV=py34-django-111
    - python: 3.4
      env: TOXENV=py34-django-20
    - python: 3.5
      env: TOXENV=py35-django-111
    - python: 3.5
      env: TOXENV=py35-django-20
    - python: 3.5
      env: TOXENV=py35-django-21
    - python: 3.5
      env: TOXENV=py35-django-22
    - python: 3.5
      env: TOXENV=py35-django-master
    - python: 3.6
      env: TOXENV=py36-django-111
    - python: 3.6
      env: TOXENV=py36-django-20
    - python: 3.6
      env: TOXENV=py36-django-21
    - python: 3.6
      env: TOXENV=py36-django-22
    - python: 3.6
      env: TOXENV=py36-django-master
    - python: 3.7
      env: TOXENV=py37-django-111
    - python: 3.7
      env: TOXENV=py37-django-20
    - python: 3.7
      env: TOXENV=py37-django-21
    - python: 3.7
      env: TOXENV=py37-django-22
    - python: 3.7
      env: TOXENV=py37-django-master
install:
    - mkdir -p $PIP_WHEEL_DIR
    - pip wheel -r tests/requirements.txt tox coveralls
    - pip install coveralls tox
script:
  - tox
after_success:
  - coveralls
